### ISSUE TITLE
Demo Level Design

### ISSUE THREAD

**Issue by matthewmau** [Kahraymer/Runner-Game#25]
Demo level design for the opening scene. Keep a cyberpunk theme in mind.
Should include background elements as part of the tutorial.
1/3 through the level add reverse gravity spaces, i.e. roof.
Use labeled colored blocks in place of sprites: to be switched out later.

**Comment by KremerTom** [comment]
Level design is done and should be available to play with. The level is called Tutorial, and it is in my folder.

Note, I'm assuming most (if not all) sprites will be replaced. I also could not figure out a way to have written instructions (Tap left side of screen to jump!) as part of background behind character.

Design:

My goal was to introduce the player to the mechanics of the game, the pace of levels, and how the player interacts with the world. I start with small spikes to introduce jumping, then a taller spike to show that you can jump at varying heights. Then I purposefully put a spike that is too tall to jump over, followed by a battery pack, so that the player can see that 1) he/she does not die, only loses juice and 2) Battery packs can help restore some juice. I add more spikes in varying patterns to let the character learn that jump timing is important in this game and to give him/her a chance to become more comfortable with the jump arc. Then, once gravity is flipped, I slowly reintroduce clearable spikes so the player understands that jumping works upside down as well.

I only put three coins in the level. The first is almost unavoidable, the second requires that the player have some dexterity to clear an upside-down tall spike, and the third requires that the player either play the tutorial twice or be extremely deft at videogames to understand that he/she should jump as gravity switches back. The goal is that the three coins are a measurement of success in the level beyond simply completing it, and thus the player learns that getting all the coins in a level is not trivial.
